#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential',
    :git => 'https://github.com/opscode-cookbooks/build-essential.git'

cookbook 'apt',
    :git => 'https://github.com/opscode-cookbooks/apt.git'

cookbook 'postgresql',
    :git => 'https://github.com/fjsj/cookbook-postgresql-9.2.git'