#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt',
    :git => 'https://github.com/opscode-cookbooks/apt.git'

cookbook 'build-essential',
    :git => 'https://github.com/opscode-cookbooks/build-essential.git'

cookbook 'python',
    :git => 'https://github.com/opscode-cookbooks/python.git'

cookbook 'django-native-deps',
    :path => 'django-native-deps'

cookbook 'postgresql',
    :git => 'https://github.com/opscode-cookbooks/postgresql.git'

cookbook 'nginx',
    :git => 'https://github.com/opscode-cookbooks/nginx.git'

cookbook 'default',
    :path => 'default'
